export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_REFRESH_TOKEN = 'AUTH_REFRESH_TOKEN';
export const CLEAN_UP = 'CLEAN_UP';

export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const SET_IS_LOGGED = 'SET_IS_LOGGED';
export const SET_IS_ADMIN = 'SET_IS_ADMIN';

export const SET_CART_ITEMS = 'SET_CART_ITEMS';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const PLUS_CART_ITEM = 'PLUS_CART_ITEM';
export const MINUS_CART_ITEM = 'MINUS_CART_ITEM';
export const CLEAR_CART = 'CLEAR_CART';
export const CART_ORDER = 'CART_ORDER';
export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const SET_CATEGORIES_START = 'SET_CATEGORIES_START';
export const SET_CATEGORIES_SUCCESS = 'SET_CATEGORIES_SUCCESS';
export const SET_CATEGORIES_FAIL = 'SET_CATEGORIES_FAIL';

export const SET_PRODUCT_START = 'SET_PRODUCT_START';
export const SET_PRODUCT_SUCCESS = 'SET_PRODUCT_SUCCESS';
export const SET_PRODUCT_FAIL = 'SET_PRODUCT_FAIL';

export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_SORT_BY = 'SET_SORT_BY';
